id: P009344
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG11803
  title: གྲུབ་མཐའ་བཞིའི་ལུགས་ཀྱི་ཀུན་རྫོབ་དང་དོན་དམ་པའི་དོན་རྣམ་པར་བཤད་པ།
  author: ''
  volumes:
    8772995b9f5947d38a905c1b4ae3b588:
      image_group_id: I1KG11810
      title: ''
      volume_number: 1
      total_pages: 230
      base_file: v001.txt
